### ISSUE TITLE
Pixel 6 android 14 截图 超过一张后报错

### ISSUE THREAD

**Issue by seventhrui** [MagicianGuo/Android-MediaProjectionDemo#3]
FATAL EXCEPTION: main
Process: com.magicianguo.mediaprojectiondemo, PID: 14547
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.Image.getWidth()' on a null object reference
	at com.magicianguo.mediaprojectiondemo.service.MediaProjectionService.screenshot(MediaProjectionService.java:160)
	at com.magicianguo.mediaprojectiondemo.view.ScreenshotView$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	
Process: com.magicianguo.mediaprojectiondemo, PID: 14845
java.lang.RuntimeException: Unable to create service com.magicianguo.mediaprojectiondemo.service.MediaProjectionService: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{f66a659 14845:com.magicianguo.mediaprojectiondemo/u0a322} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [andr
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4925)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2407)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{f66a659 14845:com.magicianguo.mediaprojectiondemo/u0a322} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media] 
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3183)
	at android.os.Parcel.createException(Parcel.java:3167)
	at android.os.Parcel.readException(Parcel.java:3150)
	at android.os.Parcel.readException(Parcel.java:3092)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6960)
	at android.app.Service.startForeground(Service.java:863)
	at com.magicianguo.mediaprojectiondemo.util.NotificationHelper.startMediaProjectionForeground(NotificationHelper.java:65)
	at com.magicianguo.mediaprojectiondemo.service.MediaProjectionService.onCreate(MediaProjectionService.java:62)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4912)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2407) 
	at android.os.Handler.dispatchMessage(Handler.java:107) 
	at android.os.Looper.loopOnce(Looper.java:232) 
	at android.os.Looper.loop(Looper.java:317) 
	at android.app.ActivityThread.main(ActivityThread.java:8592) 

                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) 
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2842)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2530)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1806)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:13793)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3483)

**Comment by ghost** [comment]
之前看到一篇文章说virtualDispaly只能使用一次,可以改变width或height解决或者重新创建VirtualDispaly,你可以试试
